# Generated by Django 3.1.6 on 2021-03-11 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebudget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 11, 9, 11, 58, 358224)),
        ),
    ]
