# Generated by Django 3.1.6 on 2021-03-11 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebudget', '0002_income_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 11, 9, 16, 15, 663442)),
        ),
        migrations.AlterField(
            model_name='income',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 11, 9, 16, 15, 663901)),
        ),
    ]
