# Generated by Django 3.1.6 on 2021-03-11 09:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebudget', '0003_auto_20210311_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 11, 9, 28, 56, 171149)),
        ),
        migrations.AlterField(
            model_name='income',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 11, 9, 28, 56, 171480)),
        ),
    ]
