# Generated by Django 3.1.6 on 2021-03-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebudget', '0006_auto_20210312_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='timestamp',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='income',
            name='timestamp',
            field=models.DateField(),
        ),
    ]
