# Generated by Django 3.1.6 on 2021-03-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebudget', '0012_auto_20210313_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
