# Generated by Django 3.1.6 on 2021-03-26 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homebudget', '0026_auto_20210326_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homebudget.category'),
        ),
    ]
