# Generated by Django 3.1.6 on 2021-04-08 13:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebudget', '0027_auto_20210326_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='timestamp',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='income',
            name='timestamp',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
