# Generated by Django 3.1.6 on 2021-04-08 13:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebudget', '0029_auto_20210408_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='timestamp',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='income',
            name='timestamp',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
