# Generated by Django 3.1.6 on 2021-04-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebudget', '0032_auto_20210408_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='timestamp',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='income',
            name='timestamp',
            field=models.DateField(),
        ),
    ]
