# Generated by Django 3.1.6 on 2021-04-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebudget', '0033_auto_20210410_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='income',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
